config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/index'
  get 'static_pages/about'
  get 'about',to:"static_pages#about"
  get 'generate_pdf', to: 'activities#generate_pdf', as: 'generate_pdf_user'
  devise_for :users
  resources :activities do
    collection do
      get 'stats'
    end
  end

  root 'static_pages#index'

end

app/models/activity.rb
class Activity < ApplicationRecord
    belongs_to :user
    has_one_attached :image
    validates :image, presence: true
    validates :calories, numericality: { 
        only_integer: true, 
        message: "only integer value"
    }
    validates :duration, numericality: { 
        only_integer: true, 
        message: "only integer value"
    }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :activities, dependent: :destroy 
  
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: %i[ show edit update destroy ]

  # GET /activities or /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1 or /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  def stats
    @total_duration = Activity.sum(:duration)
    @total_calories = Activity.sum(:calories)
  end
  
  def generate_pdf
    @activities = current_user.activities # or use any other query to fetch activities
    respond_to do |format|
      format.pdf do
        pdf = Prawn::Document.new
        pdf.font_size 18
        pdf.text "Activities", style: :bold, align: :center,font_size:50 
        pdf.move_down 10
        @activities.each do |activity|
          pdf.font_size 16
          pdf.text activity.title, style: :bold
          pdf.text "Activity Type: #{activity.activity_type}"
          pdf.move_down 5
          img = StringIO.open(activity.image.download)
          pdf.image img, width: 100, height: 100, position: :left
          pdf.move_down 10
          pdf.text "Start Time: #{activity.start.strftime('%Y-%m-%d %H:%M:%S')}"
          pdf.text "Duration: #{activity.duration} minutes"
          pdf.text "Calories Burned: #{activity.calories}"
          pdf.move_down 10
        end
        send_data pdf.render, filename: "activities.pdf", type: "application/pdf", disposition: "attachment"
      end
    end
  end
  

  # POST /activities or /activities.json
  def create
    @activity =  current_user.activities.build(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to activity_url(@activity), notice: "Activity was successfully created." }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1 or /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params.merge(user_id: current_user.id))
        format.html { redirect_to activity_url(@activity), notice: "Activity was successfully updated." }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end
  

  # DELETE /activities/1 or /activities/1.json
  def destroy
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to activities_url, notice: "Activity was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def activity_params
      params.require(:activity).permit(:title, :activity_type, :start, :duration, :calories, :image)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/activities/_activity.html.erb
<div id="<%= dom_id activity %>" class="card">
  <h4 class="card-title text-primary p-4"><%= activity.title %></h4>
  <% if activity.image.attached? %>
   <div class="imgf">
   <%= image_tag(activity.image) %>
   </div>
  <% end %>
  <div class="card-body p-3">
    <div class="row p-2">
      <div class="col-9">
        <h5 class="card-text"> <%= activity.activity_type %></h5>
      </div>
      <div class="col-3">
        <div class="row">
          <div class="col-6">
            <%= link_to "<i class='bi bi-pencil-square text-secondary'></i>".html_safe, edit_activity_path(activity), class: "btn btn-sm btn-secondary" %>
          </div>
          <div class="col-4">
            <%= button_to "<i class='bi bi-trash text-danger'></i>".html_safe, activity, method: :delete, class: "btn btn-sm btn-secondary" %>
          </div>
        </div>
      </div>
    </div>
    <div class="row p-2">
      <div class="col-8">
        <h6 class="card-text"><i class="bi bi-calendar text-secondary"></i> <%= activity.start.in_time_zone.strftime("%d %b, %Y %I:%M %p") %></h6>
      </div>
    </div>
    <div class="row p-2">
      <div class="col-4">
        <h5 class="card-text"><i class="bi bi-fire text-primary"></i> <%= activity.calories %></h5>
      </div>
      <div class="col-6">
        <h5 class="card-text"><i class="bi bi-clock-history text-secondary"></i> <%= activity.duration %></h5>
      </div>
    </div>
  </div>
</div>

app/views/activities/_form.html.erb
<div class="row">
  <div class="col-6">
    <div class="card mt-4 p-4">
      <%= form_with(model: activity) do |form| %>
        <% if activity.errors.any? %>
          <div style="color: red">
            <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

            <ul>
              <% activity.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group mb-2">
          <%= form.label :title, style: "display: block" %>
          <%= form.text_field :title, class: "form-control mt-2" %>
        </div>

        <div class="form-group mb-2">
          <%= form.label :activity_type, style: "display: block" %>
          <%= form.text_field :activity_type, class:"form-control mt-2" %>
        </div>

        <div class="form-group mb-2">
          <%= form.label :image, style: "display: block" %>
          <%= form.file_field :image, class:"form-control mt-2" %>
        </div>

        <div class="form-group mb-2">
          <%= form.label :start, style: "display: block" %>
          <%= form.datetime_field :start, class:"form-control mt-2" %>
        </div>

        <div class="row">
          <div class="col">
            <div class="form-group mb-2">
              <%= form.label :duration, style: "display: block" %>
              <%= form.text_field :duration, class:"form-control mt-2" %>
            </div>
          </div>
          <div class="col">
            <div class="form-group mb-2">
              <%= form.label :calories, style: "display: block" %>
              <%= form.number_field :calories, class:"form-control mt-2" %>
            </div>
          </div>
        </div>


        <div>
          <%= form.submit class: "btn mt-2 btn-primary text-dark" %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/activities/edit.html.erb
<div class="container">
  <h1 class="text-primary mt-4">Edit Activity</h1>
  <%= render "form", activity: @activity %>
  <br>
</div>
<div class="container">
  <%= link_to "Show this activity", @activity ,class:"btn btn-info"%> |
  <%= link_to "Back to activities", activities_path,class:"btn btn-alternate" %>
</div>

app/views/activities/index.html.erb
<div class="container">
  <h1 class="text-primary">
    Activities
    <small><%= link_to "<i class='bi bi-plus-square-fill text-primary mx-2'></i>".html_safe, new_activity_path %></small>
  </h1>
  <div id="activities" class="mt-4 card-deck">
  <% @activities.each do |activity| %>
    <div class=" col-sm-12 col-md-6 col-lg-4">
      <%= render activity %>
    </div>
  <% end %>
  </div>

  <%= link_to "Download PDF", generate_pdf_user_path(format: "pdf"),class:"btn btn-success" %>

</div>

app/views/activities/new.html.erb
<div class="container">
  <h1 class="text-primary mt-4">New activity</h1>
  <%= render "form", activity: @activity %>
  <br>
</div>

app/views/activities/show.html.erb
<div class="container">
  <%= render @activity %>
</div>
<div class="container">
  <%= link_to "Back to activities", activities_path,class:"btn btn-alternate" %>
</div>

app/views/activities/stats.html.erb
  <div class="container">
   <div class="card text-center" style="width:35%">
     <h1 class="card-title text-info">Activities Statistics</h1><br>
      <div class="card-body">
        <p class="card-text"><strong><i class="bi bi-clock-fill orange-text"></i> Total Duration:</strong> <%= @total_duration %></p><br>
        <p><strong><i class="bi bi-fire orange-text"></i> Total Calories:</strong> <%= @total_calories %></p>
      </div>
   </div>
  </div>
<div class="container">

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActivityTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%# <link href="" rel="stylesheet"> %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "dark-mode", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <%= javascript_importmap_tags %>

  <body>
   <div class="navb col-3">
    <%= render partial: 'shared/navbar' %>
   </div>
   <div class="bdy col-9">
    <%if notice%>
      <%if notice=='Activity was successfully destroyed.'%>
           <div class="container" style="justify-content:center">
            <div class=" col-sm-12 col-md-6 col-lg-4" >
             <div class="card mx-4">
               <div class="card-header bg-secondary text-center">
                 <strong><p class="font-style"><i class="bi bi-bell-fill orange-text"></i> Activity Tracker</p></strong> 
               </div>
               <div class="card-body bg-danger">
                 <strong class="font-spy"><%= notice %></strong>
               </div>
             </div>
            </div>
        </div>
      <%elsif notice=='Activity was successfully updated.'%>
           <div class="container" style="justify-content:center">
            <div class=" col-sm-12 col-md-6 col-lg-4" >
             <div class="card mx-4">
               <div class="card-header bg-secondary text-center">
                 <strong><p class="font-style"><i class="bi bi-bell-fill orange-text"></i> Activity Tracker</p></strong> 
               </div>
               <div class="card-body bg-info">
                 <strong class="font-spy"><%= notice %></strong>
               </div>
             </div>
            </div>
        </div>        
      <%else%>
        <div class="container" style="justify-content:center">
          <div class=" col-sm-12 col-md-6 col-lg-4" >
             <div class="card mx-4 ">
               <div class="card-header bg-secondary text-center">
                 <strong><p class="font-style"><i class="bi bi-bell-fill orange-text"></i> Activity Tracker</p></strong> 
               </div>
               <div class="card-body bg-success">
                 <strong class="font-spy"><%= notice %></strong>
               </div>
             </div>
            </div>
        </div>
       <%end%> 
    <%end%>
    <p class="alert"><%= alert %></p>
    <%= yield %>
   </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg p-3">
  <div class="profile">
    <ul class="navbar-nav">
      <li class="nav-item active ">

     <%if user_signed_in? %>
      <strong><a><i class="bi bi-person-circle font-sle"></i> </a></strong>
      <div class="  font-sty"><%= current_user.email%></div><br><br>
     <%else%> 
     <div class="sy" style="display:flex">
      <div class="yu" style="padding-top:2rem">
        <strong><a><i class="bi bi-person-circle font-sle"></i> </a></strong>
      </div>
      <div class="user" style="display:block;justify-content:space-between">
        <a class="nav-link   font-sty" href="/users/sign_in"><p> Sign In</p></a>
        <a class="nav-link   font-sty" href="/users/sign_up"><p> Sign Up</p></a><br>
      </div>
     </div>
     <%end%>
      </li>
    </ul>
  </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="list">
    <ul class="navbar-nav">
      <li class="nav-item active ">
        <strong><a class="nav-link  font-sle" href="/"><i class="fa-solid fa-house"></i> Home</a></strong>
      </li>
    </ul>

    <ul class="navbar-nav">
      <li class="nav-item active ">
        <strong><a class="nav-link  font-sle" href="/about"><i class="fa-sharp fa-solid fa-circle-info"></i> About</a></strong>
      </li>
    </ul>


    <%if user_signed_in? %>
    <ul class="navbar-nav">
      <li class="nav-item active ">
        <strong><a class="nav-link  font-sle" href="/activities/stats"><i class="fa-solid fa-chart-simple"></i> Statistics</a></strong>
      </li>
    </ul>
    <ul class="navbar-nav">
      <li class="nav-item active ">
        <strong><a class="nav-link  font-sle" href="/users/edit"><i class="fa-solid fa-pen-to-square"></i> Edit Account</a></strong>
      </li>
    </ul>
    <ul class="navbar-nav">
      <li class="nav-item active ">
        <strong><a class="nav-link  font-sle" href="/activities"><i class="fa-sharp fa-solid fa-person-running"></i> Activities</a></strong>
      </li>
    </ul>
    </div>
    <div style="margin-left:15px;display:flex">
      <i class="bi bi-box-arrow-in-left  font-sle"></i>    
      <%=button_to "Logout",destroy_user_session_path, method: :delete,class:"btn btn-danger" %>
    </div>  
    <%end%>
</nav>

app/views/static_pages/about.html.erb
<div class="container">
<h1 class="orange-text">ABOUT</h1>
<p>This is a fitness app</p><br>
<%= link_to "Return to Home", static_pages_index_path,class:"btn btn-alternate" %>
</div>

app/views/static_pages/index.html.erb
<div class="container" style="margin-top:150px">
  <div class="card text-center">
     <h1 class="orange-text font-st">Welcome to Activity Tracker!!!</h1>
     <%if user_signed_in? %>
      <div class=" font-sty">Logged in as: <%=current_user.email%></div><br><br>
  </div>
      <%=link_to "Edit Account Settings",edit_user_registration_path,class:"btn btn-info"%>
      <%=link_to "Go to Activities",activities_path,class:"btn btn-success"%>
</div>
<%else%>
  <div class="container">
    <br><%=link_to "Sign In",new_user_session_path,class:"btn btn-info"%><br><br>
    <%=link_to "Sign Up",new_user_registration_path,class:"btn btn-alternate"%>
  </div>
<%end%>